config/routes.rb
Rails.application.routes.draw do

  resources :accs
  resources :products do 
    collection {post :import}
  end

  root  "products#index"

end

app/models/acc.rb
class Acc < ActiveRecord::Base
end

app/models/product.rb
class Product < ActiveRecord::Base
  require 'csv'
  require 'roo'


  def self.import(file)
   spreadsheet = open_spreadsheet(file)
    header = spreadsheet.row(1)
    (2..spreadsheet.last_row).each do |i|
      row = Hash[[header, spreadsheet.row(i)].transpose]
    product = find_by_id(row["id"]) || new
    product.attributes = row.to_hash.slice(*row.to_hash.keys)
    product.save!
    end
end

  def self.open_spreadsheet(file)
  case File.extname(file.original_filename)
  when '.csv' then Roo::CSV.new(file.path, csv_options: {encoding: "iso-8859-1:utf-8"})
  when ".xls" then Roo::Excel.new(file.path, packed: nil, file_warning: :ignore)
  when ".xlsx" then Roo::Excelx.new(file.path, packed: nil, file_warning: :ignore)

  else raise "Unknown file type: #{file.original_filename}"
  end
end
end # end class 

app/controllers/accs_controller.rb
class AccsController < ApplicationController
  before_action :set_acc, only: [:show, :edit, :update, :destroy]

  # GET /accs
  # GET /accs.json
  def index
    @accs = Acc.all
  end

  # GET /accs/1
  # GET /accs/1.json
  def show
  end

  # GET /accs/new
  def new
    @acc = Acc.new
  end

  # GET /accs/1/edit
  def edit
  end

  # POST /accs
  # POST /accs.json
  def create
    @acc = Acc.new(acc_params)

    respond_to do |format|
      if @acc.save
        format.html { redirect_to @acc, notice: 'Acc was successfully created.' }
        format.json { render :show, status: :created, location: @acc }
      else
        format.html { render :new }
        format.json { render json: @acc.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accs/1
  # PATCH/PUT /accs/1.json
  def update
    respond_to do |format|
      if @acc.update(acc_params)
        format.html { redirect_to @acc, notice: 'Acc was successfully updated.' }
        format.json { render :show, status: :ok, location: @acc }
      else
        format.html { render :edit }
        format.json { render json: @acc.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accs/1
  # DELETE /accs/1.json
  def destroy
    @acc.destroy
    respond_to do |format|
      format.html { redirect_to accs_url, notice: 'Acc was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_acc
      @acc = Acc.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def acc_params
      params.require(:acc).permit(:username)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]


 def import
    Product.import(params[:file])
    redirect_to root_url, notice: "Products imported."
  end

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name)
    end
end

app/helpers/accs_helper.rb
module AccsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/accs/_form.html.erb
<%= form_for(@acc) do |f| %>
  <% if @acc.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@acc.errors.count, "error") %> prohibited this acc from being saved:</h2>

      <ul>
      <% @acc.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/accs/edit.html.erb
<h1>Editing Acc</h1>

<%= render 'form' %>

<%= link_to 'Show', @acc %> |
<%= link_to 'Back', accs_path %>

app/views/accs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Accs</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @accs.each do |acc| %>
      <tr>
        <td><%= acc.username %></td>
        <td><%= link_to 'Show', acc %></td>
        <td><%= link_to 'Edit', edit_acc_path(acc) %></td>
        <td><%= link_to 'Destroy', acc, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Acc', new_acc_path %>

app/views/accs/new.html.erb
<h1>New Acc</h1>

<%= render 'form' %>

<%= link_to 'Back', accs_path %>

app/views/accs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @acc.username %>
</p>

<%= link_to 'Edit', edit_acc_path(@acc) %> |
<%= link_to 'Back', accs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Export</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<%= flash[:notice] %>
<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Name</th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.id %></td>
        <td><%= product.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<div>
<h3>Import a CSV File</h3>
  <%= form_tag import_products_path, multipart: true do %>
    <%= file_field_tag :file %>
    <%= submit_tag "Import CSV xls xlsx" %>
  <% end %>
</div>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>